### ISSUE TITLE
Fix css

### ISSUE THREAD

**Issue by jazxbx** [jazxbx/kanban#35]
- [ ] Remove vertical sidebar on the main page 
- [ ] Make board component scroll horizontally and vertically

![Screenshot 2024-08-19 at 7 48 28 AM](https://github.com/user-attachments/assets/52aede25-a741-478e-ae5c-e02efb47c75f)

**Comment by jazxbx** [comment]
update:
https://github.com/user-attachments/assets/5774318d-dc80-4686-9911-1e9172a5356e

**Comment by ryjw** [comment]
Nice one
